// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");

describe("payment", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Không chọn ngân hàng", async function () {
    await driver.get(
      "https://648186f4d67c15364ccc62a3--fancy-horse-7213a4.netlify.app"
    );
    await driver.manage().window().setRect({ width: 1690, height: 1050 });
    await driver.findElement(By.id(":r2:")).click();
    await driver.findElement(By.id(":r2:")).sendKeys("bachkame@gmail.com");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    await driver.findElement(By.id(":r3:")).sendKeys("12345678");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    let ele = await driver.wait(
      until.elementLocated(
        By.xpath('//*[@id="root"]/div/div[1]/div/div/ul/div[2]')
      ),
      30000
    );

    await ele.click();

    await driver.findElement(By.css(".css-m0h6ei")).click();

    let noti = await driver.wait(
      until.elementLocated(By.xpath('//*[@id="notistack-snackbar"]')),
      30000
    );

    await driver.wait(
      until.elementTextIs(noti, "Hãy chọn ngân hàng thanh toán"),
      30000
    );
  });
  it("Không chọn hoá đơn", async function () {
    await driver.get(
      "https://648186f4d67c15364ccc62a3--fancy-horse-7213a4.netlify.app"
    );
    await driver.manage().window().setRect({ width: 1690, height: 1050 });
    await driver.findElement(By.id(":r2:")).click();
    await driver.findElement(By.id(":r2:")).sendKeys("bachkame@gmail.com");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    await driver.findElement(By.id(":r3:")).sendKeys("12345678");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    let paymentTab = await driver.wait(
      until.elementLocated(
        By.xpath('//*[@id="root"]/div/div[1]/div/div/ul/div[2]')
      ),
      30000
    );

    await paymentTab.click();

    await driver
      .findElement(
        By.xpath('//*[@id="tabpanel-thanhToan"]/div/div[1]/div[3]/div/div/div')
      )
      .click();
    await driver
      .findElement(By.xpath('//*[@id="menu-"]/div[3]/ul/li[2]'))
      .click();

    await driver.findElement(By.css(".css-m0h6ei")).click();

    let noti = await driver.wait(
      until.elementLocated(By.xpath('//*[@id="notistack-snackbar"]')),
      30000
    );

    await driver.wait(
      until.elementTextIs(noti, "Hãy chọn 1 hoá đơn để thanh toán"),
      30000
    );
  });
  it("Thanh toán thành công", async function () {
    await driver.get(
      "https://648186f4d67c15364ccc62a3--fancy-horse-7213a4.netlify.app"
    );
    await driver.manage().window().setRect({ width: 1690, height: 1050 });
    await driver.findElement(By.id(":r2:")).click();
    await driver.findElement(By.id(":r2:")).sendKeys("bachkame@gmail.com");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    await driver.findElement(By.id(":r3:")).sendKeys("12345678");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    let paymentTab = await driver.wait(
      until.elementLocated(
        By.xpath('//*[@id="root"]/div/div[1]/div/div/ul/div[2]')
      ),
      30000
    );

    await paymentTab.click();

    await driver
      .findElement(
        By.xpath('//*[@id="tabpanel-thanhToan"]/div/div[1]/div[3]/div/div/div')
      )
      .click();
    await driver
      .findElement(By.xpath('//*[@id="menu-"]/div[3]/ul/li[2]'))
      .click();

    let bill = await driver.wait(
      until.elementLocated(
        By.xpath(
          '//*[@id="tabpanel-thanhToan"]/div/div[2]/div/div/div/table/tbody/tr[1]/td[1]/span/input'
        )
      ),
      30000
    );
    await bill.click();

    await driver.findElement(By.css(".css-m0h6ei")).click();

    let noti = await driver.wait(
      until.elementLocated(By.xpath('//*[@id="notistack-snackbar"]')),
      30000
    );

    await driver.wait(
      until.elementTextIs(noti, "Thanh toan thành công"),
      30000
    );
  });

  it("Thanh toán nhiều hoá đơn", async function () {
    await driver.get(
      "https://648186f4d67c15364ccc62a3--fancy-horse-7213a4.netlify.app"
    );
    await driver.manage().window().setRect({ width: 1690, height: 1050 });
    await driver.findElement(By.id(":r2:")).click();
    await driver.findElement(By.id(":r2:")).sendKeys("bachkame@gmail.com");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    await driver.findElement(By.id(":r3:")).sendKeys("12345678");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();

    let paymentTab = await driver.wait(
      until.elementLocated(
        By.xpath('//*[@id="root"]/div/div[1]/div/div/ul/div[2]')
      ),
      30000
    );

    await paymentTab.click();

    await driver
      .findElement(
        By.xpath('//*[@id="tabpanel-thanhToan"]/div/div[1]/div[3]/div/div/div')
      )
      .click();
    await driver
      .findElement(By.xpath('//*[@id="menu-"]/div[3]/ul/li[2]'))
      .click();

    await driver.wait(
      until.elementLocated(
        By.xpath(
          '//*[@id="tabpanel-thanhToan"]/div/div[2]/div/div/div/table/tbody/tr[1]/td[1]/span/input'
        )
      ),
      30000
    );

    await driver
      .findElement(
        By.xpath(
          '//*[@id="tabpanel-thanhToan"]/div/div[2]/div/div/div/table/thead/tr/th[1]/span/input'
        )
      )
      .click();

    await driver.findElement(By.css(".css-m0h6ei")).click();

    let noti = await driver.wait(
      until.elementLocated(By.xpath('//*[@id="notistack-snackbar"]')),
      30000
    );

    await driver.wait(
      until.elementTextIs(noti, "Thanh toan thành công"),
      30000
    );
  });
});
