// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('regiter_success', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('regiter_error', async function() {
    await driver.get("https://645255e5891bdf00ad4df561--fancy-horse-7213a4.netlify.app/")
    await driver.manage().window().setRect({ width: 945, height: 1030 })
    await driver.findElement(By.linkText("Đăng kí")).click()
    await driver.findElement(By.id(":r4:")).click()
    await driver.findElement(By.id(":r4:")).sendKeys("Bùi Huy Bách")
    await driver.findElement(By.id(":r5:")).sendKeys("aaa@gmail.com")
    await driver.findElement(By.id(":r6:")).sendKeys("GGG34")
    await driver.findElement(By.id(":r7:")).sendKeys("hà nội")
    await driver.findElement(By.id(":r8:")).sendKeys("12345678")
    await driver.findElement(By.id(":r9:")).sendKeys("12345678")
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    await driver.wait(until.elementLocated(By.xpath("//*[@id=\"root\"]/div[2]")), 30000)
  })
})
