# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegitersuccess():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_regitersuccess(self):
    self.driver.get("https://645255e5891bdf00ad4df561--fancy-horse-7213a4.netlify.app/")
    self.driver.set_window_size(945, 1030)
    self.driver.find_element(By.LINK_TEXT, "Đăng kí").click()
    self.driver.find_element(By.ID, ":r4:").click()
    self.driver.find_element(By.ID, ":r4:").send_keys("Bùi Huy Bách")
    self.driver.find_element(By.ID, ":r5:").send_keys("aaa@gmail.com")
    self.driver.find_element(By.ID, ":r6:").send_keys("GGG34")
    self.driver.find_element(By.ID, ":r7:").send_keys("hà nội")
    self.driver.find_element(By.ID, ":r8:").send_keys("12345678")
    self.driver.find_element(By.ID, ":r9:").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.text_to_be_present_in_element((By.XPATH, "//*[@id=\"root\"]/div[2]"), "Email đã được đăng kí"))
  
